### ISSUE TITLE
<AP> Place a warning about SanDisk cards in each manual?

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/MISC#3]
-Possible?

-Reason can be found as below mail from AU customer:
Hi there, I purchased the DOD LS470W a few weeks ago and it has been doing some strange things.....I have just visited your site after ordering through the Facebook link and noticed something about not using a SANDISK card. There was no information in the package to say not to use this card otherwise I wouldn't of used one! Whilst I am ok (if not annoyed) to have to buy another card, has damage already been done to my camera? I am hoping if it has you will honour the warranty as there was no information in my package saying not to use the SANDISK card and I didn't read to the bottom of the page about the camera. I would appreciated it if someone could contact me ASAP about this issue.

**Comment by dod-pm1** [comment]
Hi, we can only do "suggestion", which is what we are doing in our manual right now.
This has been done in EVERY manual, in the last few pages, under "SD Card" section.
The reason being, IF we clearly say that it does NOT work outside the package, it may cause trouble because we are potientially suggesting a negative image of Sandisk, which we have no detail or absolute proof that the process of Sandisk memory card will cause malfunction.
This has been discussed with Jeremy, RD, Paul, and I, we came to agree that the least we can do is write clearly in the manual, but it is not suggested to put any kind of these "negative" suggestions on the outter package.

To answer above questions, wrong card does not damage the dashcam itself.

**Comment by DOD-AP-Sales** [comment]
GREAT. look forward to that is about to be done. Will ask you in person about its ready date. thanks.
